default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: adspecter_dev
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: adspecter_test
  username: root
  password:
  host: localhost

staging:
  <<: *default
  database: adspecter_staging
  username: unsecure_staging_username_0913
  password: unsecure_staging_pw_0913
#  host:

production:
  <<: *default
  database: adspecter_production
  username: unsecure_prod_username_0913
  password: unsecure_prod_pw_0913
#  host:
